### ISSUE TITLE
Bug in radius values in cubes_radius() and Unif_radius()

### ISSUE THREAD

**Issue by DBobkov** [aboulch/normals_Hough#2]
Dear Alexandre,

There seems to be an inconsistency in the methods of cubes_radius() at L1682 and Unif_radius() at L1418 where the radius2 is used as it is from the input argument, while in two other methods, e.g. cubes_knn() and the Unif_knn() it is computed as follows (L1287 or L1573):  `radius = sqrt(radius);`
Is this a bug?

Best regards
Dmytro Bobkov

**Comment by aboulch** [comment]
Hello,
It was a bug, I corrected it by adding the radius2 = sqrt(radius2) to fit the two knn methods.
Thanks for spotting this bug.
Best,
Alexandre

**Comment by DBobkov** [comment]
Thank you, Alexandre!
