### ISSUE TITLE
there is  something wrong

### ISSUE THREAD

**Issue by yulihui1993** [aboulch/normals_Hough#4]
when i compile the normals_hough,it comes   
E:\normals_Hough-master\normals_Hough-master\include\Normals.h(252) : error C2664: “nanoflann::KDTreeSingleIndexAdaptor<Distance,DatasetAdaptor,DIM,IndexType>::knnSearch”: 不能将参数 3 从“long *”转换为“__w64 int *”
how can i solve this problem

**Comment by aboulch** [comment]
Hello,
I did not tried to compile on Windows, I do not know the error.
From google it says that C2664 is a type problem. Try to cast the right argument to the right type.
Hope I could help.
